"""add_delivery_tasks

Revision ID: b13f07ca8a0e
Revises: 536c5f158c29
Create Date: 2026-09-24 08:39:59.016076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b13f07ca8a0e'
down_revision: Union[str, None] = '536c5f158c29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('vendor_order_id', sa.Uuid(), nullable=False),
    sa.Column('rider_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'ACCEPTED', 'PICKED_UP', 'IN_TRANSIT', 'DELIVERED', 'FAILED', 'CANCELLED', name='deliverytaskstatus'), nullable=False),
    sa.Column('pickup_address', sa.String(length=500), nullable=False),
    sa.Column('pickup_city', sa.String(length=100), nullable=False),
    sa.Column('pickup_phone', sa.String(length=20), nullable=False),
    sa.Column('dropoff_address', sa.Text(), nullable=False),
    sa.Column('dropoff_city', sa.String(length=100), nullable=False),
    sa.Column('dropoff_phone', sa.String(length=20), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('dispatch_earnings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('verification_code', sa.String(length=10), nullable=False),
    sa.Column('verification_attempts', sa.Integer(), nullable=False),
    sa.Column('max_verification_attempts', sa.Integer(), nullable=False),
    sa.Column('verification_code_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verification_code_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_order_id'], ['vendor_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_tasks_order_id'), 'delivery_tasks', ['order_id'], unique=False)
    op.create_index(op.f('ix_delivery_tasks_rider_id'), 'delivery_tasks', ['rider_id'], unique=False)
    op.create_index(op.f('ix_delivery_tasks_status'), 'delivery_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_delivery_tasks_vendor_order_id'), 'delivery_tasks', ['vendor_order_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_tasks_vendor_order_id'), table_name='delivery_tasks')
    op.drop_index(op.f('ix_delivery_tasks_status'), table_name='delivery_tasks')
    op.drop_index(op.f('ix_delivery_tasks_rider_id'), table_name='delivery_tasks')
    op.drop_index(op.f('ix_delivery_tasks_order_id'), table_name='delivery_tasks')
    op.drop_table('delivery_tasks')
    # ### end Alembic commands ###
